site_name: virt-roles
repo_url: https://github.com/virt-roles/virt-roles
theme:
  name: material
nav:
  - Home: index.md
  - why.md
  - Common recipes:
    - qemu-from-source.md
    - qemu-rpm-installation.md
